/********************************************************************************
 *              Copyright (C) Joint Institute for Nuclear Research              *
 *                                                                              *
 *              This software is distributed under the terms of the             *
 *         GNU Lesser General Public Licence version 3 (LGPL) version 3,        *
 *                  copied verbatim in the file "LICENSE"                       *
 ********************************************************************************/
#ifndef ERNDTrack_H
#define ERNDTrack_H

#include "TVector3.h"

class ERNDTrack : public TObject {
  public:
    ERNDTrack() = default;
    ERNDTrack(const TVector3& detectorVertex, Bool_t isN1, Bool_t isN2, const TVector3& targetVertex,
              float edep, float edep_n1, float edep_n2, float time, float time_n1, float time_n2, float tac);	
    /** Accessors **/
    TVector3 DetectorVertex() const {return fDetectorVertex;}
    TVector3 TargetVertex() const {return fTargetVertex;}
    TVector3 Direction() const;
    float Edep() const {return fEdep;}
    float Edep_n1() const {return fEdep_n1;}
    float Edep_n2() const {return fEdep_n2;}
    float Time() const {return fTime;}
    float Time_n1() const {return fTime_n1;}
    float Time_n2() const {return fTime_n2;}
    float TAC() const {return fTAC;}
    Bool_t IsN1() const {return fIsN1;}
    Bool_t IsN2() const {return fIsN2;}
  protected:
    TVector3 fTargetVertex;
    TVector3 fDetectorVertex;
    float fEdep = -1.;
    float fEdep_n1 = -1.;
    float fEdep_n2 = -1.;
    float fTime = -1.;
    float fTime_n1 = -1.;
    float fTime_n2 = -1.;
    float fTAC = -1.;
    Bool_t fIsN1 = kFALSE;	//keys to understand if track is generated by 1st 
    Bool_t fIsN2 = kFALSE;	//or 2nd neutron
    ClassDef(ERNDTrack,1)
};

#endif
