#! /bin/bash

usage()
{
    printf "Usage: $0 -f FILENAME [-h]\n\n\
This script converts an unpacked ROOT file from an LMD file with raw data to a ROOT file with a structure \n\
taken from ROOT file, which is generated by a Monte-Carlo simulation of an experiment. This file is saved \n\
with a *.digi.root extention. After that the *.digi.root file processed to remove garbage data. The \n\
result is saved in a ROOT file with a *.clean.root extension. The cleared ROOT file is then used for \n\
reconstruction of lorentz-vectors of reaction products. The result is saved in a ROOT file with a \n\
*reco.root extension. Attention! The $1 script is to be run from the root directory of the project.\n\n\
OPTIONS:\n\n\
\t-f FILENAME\t- name of the ROOT file to process;\n\
\t-h\t\t- show usage and exit.\n\n"; 
    exit 1;
}

while getopts ":f:eh" o; do
    case "${o}" in
        f)
            INPUTFILENAME=${OPTARG}
            ;;
        h)
            usage
            ;;
    esac
done

if [ -z "${INPUTFILENAME}" ]
then
    usage
fi

root -l -b -q create_target_exp1904.C
root -l -b -q create_passive_component.C
root -l -b -q 'sim_digi.C(1)'
root -l -b -q 'digibuilder.C('"\"${INPUTFILENAME}\""', '"\"${INPUTFILENAME}.digi.root\""')'
root -l -b -q 'digicleaner.C('"\"${INPUTFILENAME}.digi.root\""', '"\"${INPUTFILENAME}.clean.root\""')'
root -l -b -q 'reco.C('"\"${INPUTFILENAME}.clean.root\""', '"\"${INPUTFILENAME}.reco.root\""')'
